# Generated by Django 2.2.7 on 2021-05-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_body', models.TextField(blank=True, null=True)),
                ('query_param', models.TextField(blank=True, null=True)),
                ('headers', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'URL Detail',
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('hit_count', models.PositiveSmallIntegerField(default=0)),
                ('url_details', models.ManyToManyField(blank=True, to='core.URLDetail')),
            ],
            options={
                'verbose_name_plural': 'URL',
            },
        ),
    ]
